### ISSUE TITLE
Django Dashboard Material - sidebar navigtation active highlight

### ISSUE THREAD

**Issue by Algogator** [app-generator/django-dashboard-material#1]
When you navigate through the sidebar the highlight does not follow it. It's stuck on Dashboard.

**Comment by app-generator** [comment]
Patch proposal: 
In the controller: a new variable `segment` will be injected when the page is rendered  
In the `sidebar` component:  we need to check the current page (e.g. segment variable) and `echo` the *active* CSS class. 
We will provide the patch asap.

**Comment by app-generator** [comment]
Patch in [commit](https://github.com/app-generator/django-dashboard-material/commit/3217a844e45105b36e002f65899b7842f5743d64)

I will close the issue. 

@Algogator join the community on [Discord](https://discord.gg/fZC6hup) - It's free :)
