### ISSUE TITLE
Django Dashboard Material - textarea should automatically expand instead of using a scrollbar

### ISSUE THREAD

**Issue by Algogator** [app-generator/django-dashboard-material#2]
The textarea in the edit user profile section should automatically expand without the scrollbar

**Comment by app-generator** [comment]
Hello, 
Please provide more information regarding this issue. 
Thank you!

**Comment by Algogator** [comment]
https://materializecss.com/text-inputs.html

From the doc "Textareas allow larger expandable user input. "

**Comment by app-generator** [comment]
This is not a software fault or a bug related to the web app features. 
AppSeed will generate web apps, without altering or mutate the default JS actions. 

Anyway, juts to provide a small hint, a possible solution might be to update the [page-user.html](https://github.com/app-generator/django-dashboard-material/blob/master/core/templates/pages/page-user.html) with a specific CSS and JS:

```HTML
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
  <style>
    textarea {
      height: auto !important;
      resize: vertical;
    }
  </style>
{% endblock stylesheets %}
..
{% block content %} ... {% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script> .. </script>
{% endblock javascripts %}
 
```

Some useful links:
- [Auto expand a textarea using jQuery](https://stackoverflow.com/questions/2948230/auto-expand-a-textarea-using-jquery/10080841) - you need an extra JS dependency
- [Auto Resize Textarea Height using jQuery](https://www.codexworld.com/auto-resize-textarea-height-using-jquery/)

Hope this helps. I will close this fault.
