### ISSUE TITLE
Forgot password functionality

### ISSUE THREAD

**Issue by Algogator** [app-generator/django-dashboard-material#4]
It would be nice to have a forgot password option too.

**Comment by app-generator** [comment]
Hello @Algogator,
Thanks for using our products. This is a good idea. 
For the new features, we are using a voting system. The most voted features are implemented in all related starters (Django, Flask, ..) generated by the platform.
Take a look, if you have the time: [Appseed voting system](https://appseed.nolt.io/).
Thanks.
