### ISSUE TITLE
Error views

### ISSUE THREAD

**Issue by Algogator** [app-generator/django-dashboard-material#6]
The demo site does not seem to be using the error-404.html 

https://django-dashboard-material.appseed.us/tables

**Comment by app-generator** [comment]
Thanks, 
We are working on this. This behavior occurs outside of the private zone.

**Comment by app-generator** [comment]
Patch committed - Please update.
Thanks for your contribution - Feel free to join us on [Discord](https://discord.gg/fZC6hup)
