### ISSUE TITLE
view doesnt redirect to with slash "/" automatically

### ISSUE THREAD

**Issue by rashedoz** [app-generator/django-dashboard-material#7]
The other dashboards redirect the views without slashes to a view with a slash. But this project doesn't seem to do that.  How to redirect automatically toa a view with slash?

**Comment by app-generator** [comment]
Hello @rashedoz, 

The **Django** managed paths like `login`, `register` use `/` at the end of the URL.
The ordinary pages are loaded using a dynamic rule and `/` is not appended after the page. 

Closing.

P.S. The product is recently updated. Feel free to use the latest version.
